apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: exercises

resources:
  - postgres-secret.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - knative-service.yaml

images:
  - name: ping-pong
    newName: dev.local/ping-pong
    newTag: "1.6"
