apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-data-pvc
      containers:
        - name: log-output-writer
          image: log_output_writer:1.0
          volumeMounts:
            - name: shared-logs
              mountPath: /app/files
        - name: log-output-reader
          image: log_output_reader:1.0
          volumeMounts:
            - name: shared-logs
              mountPath: /app/files
              readOnly: true
            - name: shared-storage
              mountPath: /app/data
              readOnly: true
