apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
        - name: config
          configMap:
            name: log-output-configmap
      containers:
        - name: log-output-writer
          image: europe-north1-docker.pkg.dev/dwk-gke-507418/dwk-images/log-output-writer:1.0
          volumeMounts:
            - name: shared-logs
              mountPath: /app/files
          env:
            - name: LOG_FILE
              value: /app/files/log.txt
        - name: log-output-reader
          image: europe-north1-docker.pkg.dev/dwk-gke-507418/dwk-images/log-output-reader:1.2
          volumeMounts:
            - name: shared-logs
              mountPath: /app/files
              readOnly: true
            - name: config
              mountPath: /app/config
              readOnly: true
          env:
            - name: PORT
              value: "3000"
            - name: LOG_FILE
              value: /app/files/log.txt
            - name: INFORMATION_FILE
              value: /app/config/information.txt
            - name: PING_PONG_URL
              value: http://ping-pong-svc/pings
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: MESSAGE
