apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: exercises

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - gateway.yaml
  - httproute.yaml

images:
  - name: log-output-writer
    newTag: "1.0"
  - name: log-output-reader
    newTag: "1.3"
