apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: exercises

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- gateway.yaml
- httproute.yaml
- greeter.yaml

images:
- name: greeter
  newName: otsoh/log-output-greeter
  newTag: 88fc7167298cd8cb4ac8815c10b85d6e2d075133
- name: log-output-reader
  newName: otsoh/log-output-reader
  newTag: 88fc7167298cd8cb4ac8815c10b85d6e2d075133
- name: log-output-writer
  newName: otsoh/log-output-writer
  newTag: 88fc7167298cd8cb4ac8815c10b85d6e2d075133
